version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Berlin
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: "@tensorflow/tfjs-node"
    versions:
    - 2.8.6
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
  - dependency-name: "@tensorflow/tfjs"
    versions:
    - 3.0.0
    - 3.1.0
    - 3.2.0
    - 3.3.0
    - 3.4.0
