name: Node testing

on: [pull_request]

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12

    - name: ci and test
      run: |
        npm ci
        npm test
